#! /bin/sh
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          5
bspc config active_border_color "#c9c7cd"
bspc config focused_border_color "#ea83a5"
bspc config normal_border_color "#c9c7cd"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
# AUTO START
sxhkd &
nitrogen --restore &
picom &
pkill wireplumber
wireplumber &
setxkbmap -option
setxkbmap -option ctrl:nocaps
# change this to your mouse thingy
xinput set-prop 9 "libinput Accel Profile Enabled" 0, 1
xinput set-prop 9 "libinput Accel Speed" -0.80

#rm -rf ~/.config/chromium/Singleton* # if anything breaks with chromium again enable this
